import React from 'react'
import DashboardHeading from '../components/DashboardHeading'
import ProfileHeading from '../components/ProfileHeading'
import MainEssay from '../components/dashboard/MainEssay'
import AddNewEssay from '../components/AddNewEssay'
import Head from 'next/head'

const AddQuestionPage = () => {
  return (

    <>
    <Head>
        <title>Gradewise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <div className='h-screen'>
       <ProfileHeading />
        <div className='flex w-4/6 mx-auto h-[90%]'>
           <AddNewEssay /> 
        </div>
    </div>
    </>
  )
}

export default AddQuestionPage