import React from "react";
import DashboardHeading from "../components/DashboardHeading";
import ProfileHeading from "../components/ProfileHeading";
import MainEssay from "../components/dashboard/MainEssay";
import Head from "next/head";
const EssayPage = () => {
  return (
    <>
      <Head>
        <title>Gradewise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen">
        <ProfileHeading />
        <div className="flex w-4/6 mx-auto h-[90%]">
          <MainEssay />
        </div>
      </div>
    </>
  );
};

export default EssayPage;
