import Head from "next/head";
import LecturerLoginForm from "../components/landing-page/LecturerLogin";
import LecturerHeading from "../components/LecturerHeding";

export default function LecturerLogin() {
  return (
    <>
      <Head>
        <title>Gradewise Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <LecturerHeading />
        <LecturerLoginForm />
      </main>
    </>
  );
}
