import React from 'react'

import Head from "next/head"
import DashboardHeading from '../components/DashboardHeading'
import Sidebar from '../components/dashboard/Sidebar'
import MainDashboard from '../components/dashboard/MainDashboard'
const DashboardPage = () => {
  return (
    <>
   <Head>
        <title>Gradewise  - Student Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <div className='h-screen'>
        <DashboardHeading />
        <div className='flex w-full h-[90%]'>
            <Sidebar />
            <MainDashboard />
        </div>
    </div>
    </>
  )
}

export default DashboardPage